version: "3.9"
services:
  uiserver:
    container_name: uiserver
    env_file:
      - ui.env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - ctrl_internal
    expose:
      - 3000
      - 3001
    ports:
      - "3000:3000"
      - "3001:3001"

networks:
  ctrl_internal:
    name: intnet
    external: true
